Repository MetaFam/metagame-wiki, pull requests merged in 2021-05, with the labels that each got.

#228 Update Enter Metagame “join-metagame”
  docs/enter-metagame/join-metagame.md
Labels: netlify-cms/draft

#229 Update Great Houses “house-of-daos”
  docs/great-houses/house-of-daos.md
Labels: netlify-cms/draft

#230 Create wiki page for calendar
  docs/resources/calendar.mdx
  sidebars.js
  src/components/signpost.js
Labels: documentation, enhancement

#235 Update Resources “glossary”
  docs/resources/glossary.md
Labels: netlify-cms/pending_publish

#236 Update How Does It Work “xp”
  docs/how-does-it-work/xp.md
Labels: netlify-cms/pending_publish
